# Generated by Django 4.1.2 on 2022-10-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='home.coments'),
        ),
    ]
